using DLL;
using System;
using System.Collections.Generic;

namespace BLL
{
    public class PostsLicitaciones
    {

        public PostsLicitaciones()
        {
            ListPostsLicitaciones = new List<Post>();
            LoadPostDataLicitaciones();
        }

        public List<Post> ListPostsLicitaciones { get; set; }

        private void LoadPostDataLicitaciones()
        {
            ListPostsLicitaciones.Add(
                new Post
                {
                    Id = 1,
                    Descripcion = "En la visualización se puede apreciar cuánto utilizan las entidades del Gobierno Central la modalidad de Licitación Pública (LP), medida en términos del monto que se transa. El tamaño de la burbuja representa el % del monto comprado que se hizo a través de LP respecto del total de compras realizadas por la entidad. La intensidad del color de la burbuja, representa la importancia del monto transado por la entidad respectiva utilizando LP, en relación a la totalidad del monto transado en LP en el mercado público (Gobierno Central). Al posicionarse sobre cualquiera de las burbujas, se desplegará un cuadro con el detalle de lo transado por esa entidad en las distintas modalidades de compra, tanto en términos del monto, como de la cantidad de transacciones.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535850288369' style='position: relative'><noscript><a href='#'><img alt='Lic Pública ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;1y&#47;1y2_mobile&#47;LicPblica&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='1y2_mobile&#47;LicPblica' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;1y&#47;1y2_mobile&#47;LicPblica&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535850288369');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1543520809187' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;LP&#47;LP1&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='LP1&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;LP&#47;LP1&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1543520809187');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "Cuanto_se_utiliza_la_Licitacion_Publica",
                    Pregunta = "¿Cuánto se utiliza la Licitación Pública?",
                    RedTitulo = "¿Cuánto se utiliza la Licitación Pública?  - Observatorio de Compras",
                    RedDescripcion= "Aquí puedes conocer, cuánto utiliza el Gobierno Central la modalidad de Licitación Pública (LP). El tamaño de la burbuja representa el porcentaje del monto comprado, que se hizo a través de LP, respecto del total de compras realizadas por la entidades del Gobierno.",
                    RedUrl= "Cuanto_se_utiliza_la_Licitacion_Publica",
                    RedImagen= "Timg1_1.png"
                }
            );
            ListPostsLicitaciones.Add(
                new Post
                {
                    Id = 2,
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535850532752' style='position: relative'><noscript><a href='#'><img alt='Dashboard 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;3y&#47;3y4_mobile&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='3y4_mobile&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;3y&#47;3y4_mobile&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535850532752');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1543520864012' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;LP&#47;LP2&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='LP2&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;LP&#47;LP2&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1543520864012');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    Descripcion = "En la visualización se puede apreciar la distribución de la cantidad de oferentes por licitación adjudicada, cada barra está sub-dividida según ministerios, donde la altura de la barra corresponde a la cantidad de licitaciones que tuvieron X cantidad de oferentes.<br> La intensidad del color corresponde al volumen de monto adjudicado en licitaciones con la respectiva cantidad de oferentes. Al posicionarse sobre alguna de las categorías, se despliegará un cuadro con los 10 Servicios Públicos que más presentan esa cantidad de oferentes, con la cantidad respectiva de licitaciones, y el monto adjudicado. <br><br> Nota: Se excluyen del análisis el Ministerio de Obras Públicas y el SERVIU, ya que la información de las ofertas no siempre se encuentra cargada como dato en la plataforma.",
                    IdUrl = "Cuantos_oferentes_tienen_las_licitaciones",
                    Pregunta = "¿Cuántos oferentes tienen las licitaciones?",
                    RedTitulo = "¿Cuántos oferentes tienen las licitaciones?  - Observatorio de Compras",
                    RedDescripcion = "En la visualización se puede apreciar la distribución de la cantidad de oferentes por licitación.",
                    RedUrl = "Cuantos_oferentes_tienen_las_licitaciones",
                    RedImagen = "Timg1_2.png"

                }
            );
            ListPostsLicitaciones.Add(
                new Post
                {
                    Id = 3,
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535850576976' style='position: relative'><noscript><a href='#'><img alt='Dashboard 2 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;3y&#47;3y4_mobile&#47;Dashboard2&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='3y4_mobile&#47;Dashboard2' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;3y&#47;3y4_mobile&#47;Dashboard2&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535850576976');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1543520897530' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;LP&#47;LP3&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='LP3&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;LP&#47;LP3&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1543520897530');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    Descripcion = "La visualización presenta la cantidad de oferentes por rubro, donde el área de cada rectángulo está determinada por la cantidad de licitaciones que se adjudicaron en el rubro seleccionado, con la cantidad de oferentes respectiva.<br>La intensidad del color corresponde al monto adjudicado en el rubro seleccionado, con la cantidad de oferentes correspondientes, respecto del total de monto adjudicado en el rubro. Al posicionarse sobre un rectángulo, se desplegará un cuadro con los 10 Servicios Públicos que más licitaciones han tenido con la cantidad de oferentes respectivas, en el rubro seleccionado, asimismo, se presenta la intensidad de color como el monto adjudicado por cada entidad.<br><br>*Se excluyeron del análisis el MOP y los SERVIU, debido a que presentan un uso de la plataforma que no permite determinar la cantidad de oferentes.",
                    IdUrl = "Cuantos_oferentes_por_rubro_tienen_las_licitaciones",
                    Pregunta = "¿Cuántos oferentes por rubro tienen las licitaciones?",
                    RedTitulo = "¿Cuántos oferentes por rubro tienen las licitaciones?  - Observatorio de Compras",
                    RedDescripcion = "La visualización presenta la cantidad de oferentes por rubro.",
                    RedUrl = "Cuantos_oferentes_por_rubro_tienen_las_licitaciones",
                    RedImagen = "Timg1_3.png"
                }
            );
            ListPostsLicitaciones.Add(
                new Post
                {
                    Id = 4,
                    Descripcion = "En la visualización se puede apreciar la distribución de la cantidad de días abiertas de cada licitación, por abierta, se consideró desde la fecha de publicación hasta la fecha de adjudicación, donde la altura de la barra corresponde a la cantidad de licitaciones que tuvieron X cantidad de días. La intensidad del color corresponde al volumen de monto adjudicado en licitaciones con la respectiva cantidad de días. Al posicionarse sobre alguna de las categorías, se desplegará un cuadro con los 10 Servicios Públicos que más presentan esa cantidad de oferentes y los 10 Servicios Públicos con el mayor volumen transado en las respectiva de licitaciones.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535850715922' style='position: relative'><noscript><a href='#'><img alt='Dashboard 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;5_&#47;5_mob&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='5_mob&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;5_&#47;5_mob&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535850715922');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1535850706001' style='position: relative'><noscript><a href='#'><img alt='Dashboard 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;5_&#47;5_519&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='5_519&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;5_&#47;5_519&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535850706001');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "Cuanto_tiempo_estan_abiertas_las_licitaciones",
                    Pregunta = "¿Cuánto tiempo están abiertas las licitaciones?",
                    RedTitulo = "¿Cuánto tiempo están abiertas las licitaciones?  - Observatorio de Compras",
                    RedDescripcion = "En la visualización se puede apreciar la distribución de la cantidad de días abiertas de cada licitación, por abierta, se consideró desde la fecha de publicación hasta la fecha de adjudicación, donde la altura de la barra corresponde a la cantidad de licitaciones que tuvieron X cantidad de días.",
                    RedUrl = "Cuanto_tiempo_estan_abiertas_las_licitaciones",
                    RedImagen = "Timg1_4.png"
                }
            );
            ListPostsLicitaciones.Add(
                new Post
                {
                    Id = 5,
                    Descripcion = "En la visualización interactiva se presenta la relación entre dueños de empresa, empresas y ofertas a licitaciones, en particular la información presentada corresponde a todas aquellas licitaciones en las que el dueño de una empresa postuló a través de más de una empresa a la misma licitación con ofertas distintas. Al posicionarse sobre cada nodo, se despliega un detalle con las características de este. De la misma manera, al posicionarse sobre un link, se despliegan los detalles de las relaciones correspondientes Las flechas destacadas en rojo, corresponden a ofertas adjudicadas.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535850926094' style='position: relative'><noscript><a href='#'><img alt='Dashboard 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;8_&#47;8_mob&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='8_mob&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;8_&#47;8_mob&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535850926094');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1535850830054' style='position: relative'><noscript><a href='#'><img alt='Dashboard 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;8_&#47;8_128&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='8_128&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;8_&#47;8_128&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535850830054');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "Existen_socios_que_postulen_a_una_misma_Licitacion_Publica_con_distintas_empresas",
                    Pregunta = "¿Existen socios que postulen a una misma Licitación Pública con distintas empresas?",
                    RedTitulo = "¿Existen socios que postulen a una misma Licitación Pública con distintas empresas?  - Observatorio de Compras",
                    RedDescripcion = "En la visualización se presenta un listado de socios dueños de empresas (eje y), donde el tamaño de la barra asociado a cada dueño de empresa corresponde a la cantidad de empresas asociadas a cada uno, que han sido utilizadas para ofertar a una misma licitación, es decir, si dos empresas pertenecen a un empresario, y estas dos empresas fueron utilizadas para hacer ofertas a una misma licitación, estas dos empresas fueron consideradas, sin embargo si el empresario tiene una tercera empresa que no ha sido utilizada de esta forma, no se considera dentro del conteo. El periodo analizado corresponde a los años 2013 a 2017. La intensidad del color corresponde al monto adjudicado en licitaciones a empresas de ese dueño de empresa. Al posicionarse sobre una barra se despliega el detalle de las empresas pertenecientes a la persona, y con ellas los montos adjudicados, las ofertas realizadas y las adjudicaciones logradas",
                    RedUrl = "Existen_socios_que_postulen_a_una_misma_Licitacion_Publica_con_distintas_empresas",
                    RedImagen = "Timg1_5.png"
                }
            );
            ListPostsLicitaciones.Add(
                new Post
                {
                    Id = 6,
                    Descripcion = "La visualización presenta las compras Servicio - Proveedor para el periodo seleccionado en el filtro presente a la derecha. El tamaño de la burbuja corresponde al porcentaje de compras que el municipio realiza al respectivo proveedor, y mientras que el color de las burbujas se puede seleccionar entre la cantidad de órdenes de compra o el monto comprado, tomando como referencia el mercado de compras totales del Ministerio seleccionado, en el período seleccionado. Es decir, a mayor tamaño de la burbuja, mayor la importancia de la relación comprador - proveedor sobre las compras del Servicio para el período seleccionado, y mientras más oscura sea la burbuja, mayor la cantidad de órdenes de compra o el monto transado respecto del mercado de compras del Ministerio.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535851610683' style='position: relative'><noscript><a href='#'><img alt='Dashboard1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;6_&#47;6_mobile&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='6_mobile&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;6_&#47;6_mobile&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535851610683');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1543520939160' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;LP&#47;LP4&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='LP4&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;LP&#47;LP4&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1543520939160');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "A_que_empresas_le_compra_el_Gobierno",
                    Pregunta = "¿A qué empresas le compra el Gobierno?",
                    RedTitulo = "¿A qué empresas le compra el Gobierno?  - Observatorio de Compras",
                    RedDescripcion = "La visualización presenta las compras Servicio - Proveedor para un periodo en especifico.",
                    RedUrl = "A_que_empresas_le_compra_el_Gobierno",
                    RedImagen = "Timg1_6.png"
                }
            );
        }
    }

    public class PostsTrato
    {

        public PostsTrato()
        {
            ListPostsTrato = new List<Post>();
            LoadPostDataTrato();
        }

        public List<Post> ListPostsTrato { get; set; }

        private void LoadPostDataTrato()
        {

            ListPostsTrato.Add(
                new Post
                {
                    Id = 1,
                    Descripcion = "En la visualización se puede apreciar los compradores que utilizan el trato directo con grandes sumas de dinero, del Gobierno Central. El tamaño de la burbuja representa el monto comprado que se hizo a través de TD respecto del total de compras realizadas por TD en todo el mercado público. La intensidad del color de la burbuja, representa el % del monto transado por la entidad respectiva utilizando TD, en relación a la totalidad del monto transado por la misma entidad. Al posicionarse sobre cualquiera de las burbujas, se desplegará un cuadro con el detalle de lo transado por esa entidad en las distintas modalidades de compra, tanto en términos del monto, como de la cantidad de transacciones.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1538582095481' style='position: relative'><noscript><a href='#'><img alt='Tratos directos (2) ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;1y&#47;1y2_mobile&#47;Tratosdirectos2&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='1y2_mobile&#47;Tratosdirectos2' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;1y&#47;1y2_mobile&#47;Tratosdirectos2&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1538582095481');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1543520965900' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;TD&#47;TD1_21&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='TD1_21&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;TD&#47;TD1_21&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1543520965900');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "Cuales_fueron_los_compradores_con_mayores_montos_por_trato_directo",
                    Pregunta = "¿Cuáles fueron los compradores con mayores montos por Trato Directo?",
                    RedTitulo = "¿Cuáles fueron los compradores con mayores montos por Trato Directo?  - Observatorio de Compras",
                    RedDescripcion = "La visualización muestra los compradores que utilizan el trato directo con grandes sumas de dinero - Proveedor para un periodo en especifico.",
                    RedUrl = "Cuales_fueron_los_compradores_con_mayores_montos_por_trato_directo",
                    RedImagen = "Timg2_3.png"
                }
            );
            ListPostsTrato.Add(
                new Post
                {
                    Id = 2,
                    Descripcion = "En la visualización se puede apreciar cuánto utilizan las entidades del Gobierno Central la modalidad de Trato Directo (TD), medida en términos del monto que se transa. El tamaño de la burbuja representa el % del monto comprado que se hizo a través de TD respecto del total de compras realizadas por la entidad. La intensidad del color de la burbuja, representa la importancia del monto transado por la entidad respectiva utilizando TD, en relación a la totalidad del monto transado en TD en el mercado público (Gobierno Central). Al posicionarse sobre cualquiera de las burbujas, se desplegará un cuadro con el detalle de lo transado por esa entidad en las distintas modalidades de compra, tanto en términos del monto, como de la cantidad de transacciones.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535851141806' style='position: relative'><noscript><a href='#'><img alt='Tratos directos ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;1y&#47;1y2_mobile&#47;Tratosdirectos&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='1y2_mobile&#47;Tratosdirectos' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;1y&#47;1y2_mobile&#47;Tratosdirectos&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535851141806');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1543520996743' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;TD&#47;TD2_1&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='TD2_1&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;TD&#47;TD2_1&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1543520996743');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "Que_tanto_se_utiliza_el_Trato_Directo",
                    Pregunta = "¿Qué tanto se utiliza el Trato Directo?",
                    RedTitulo = "¿Qué tanto se utiliza el Trato Directo?  - Observatorio de Compras",
                    RedDescripcion = "En la visualización se puede apreciar cuánto utilizan las entidades del Gobierno Central la modalidad de Trato Directo (TD), medida en términos del monto que se transa.",
                    RedUrl = "Que_tanto_se_utiliza_el_Trato_Directo",
                    RedImagen = "Timg2_1.png"
                }
            );
            ListPostsTrato.Add(
                new Post
                {
                    Id = 3,
                    Descripcion = "La visualización presenta las compras Servicio - Proveedor para el periodo seleccionado en el filtro presente a la derecha. El tamaño de la burbuja corresponde al porcentaje de compras que el municipio realiza al respectivo proveedor, y mientras que el color de las burbujas se puede seleccionar entre la cantidad de órdenes de compra o el monto comprado, tomando como referencia el mercado de compras totales del Ministerio seleccionado, en el período seleccionado. Es decir, a mayor tamaño de la burbuja, mayor la importancia de la relación comprador - proveedor sobre las compras del Servicio para el período seleccionado, y mientras más oscura sea la burbuja, mayor la cantidad de órdenes de compra o el monto transado respecto del mercado de compras del Ministerio.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535851610683' style='position: relative'><noscript><a href='#'><img alt='Dashboard1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;6_&#47;6_mobile&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='6_mobile&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;6_&#47;6_mobile&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535851610683');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1543521026488' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;TD&#47;TD3_1&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='TD3_1&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;TD&#47;TD3_1&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1543521026488');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "A_que_empresas_le_compra_el_Gobierno",
                    Pregunta = "¿A qué empresas le compra el Gobierno?",
                    RedTitulo = "¿A qué empresas le compra el Gobierno?  - Observatorio de Compras",
                    RedDescripcion = "La visualización presenta las compras Servicio - Proveedor para un periodo en especifico.",
                    RedUrl = "A_que_empresas_le_compra_el_Gobierno",
                    RedImagen = "Timg2_2.png"
                }
            );
        }
    }

    public class PostsConvenio
    {

        public PostsConvenio()
        {
            ListPostsConvenio = new List<Post>();
            LoadPostDataConvenio();
        }

        public List<Post> ListPostsConvenio { get; set; }

        private void LoadPostDataConvenio()
        {
            ListPostsConvenio.Add(
                new Post
                {
                    Id = 1,
                    Descripcion = "El gráfico representa la distribución del uso de los Convenios Marco, donde el tamaño de cada cuadro representa el monto transado en ese convenio, mientras que la intensidad del color representa la cantidad de órdenes de compra. Al seleccionar cualquiera de las categorías, se profundizará en el detalle de esta, mostrando la distribución por monto de los proveedores asociados al respectivo convenio.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535851288759' style='position: relative'><noscript><a href='#'><img alt='Dashboard 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;9_&#47;9_CM_mob&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='9_CM_mob&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;9_&#47;9_CM_mob&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535851288759');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1535851272064' style='position: relative'><noscript><a href='#'><img alt='Dashboard 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;9_&#47;9_CM&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='9_CM&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;9_&#47;9_CM&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535851272064');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "Quienes_se_adjudican_via_Convenios_Marco",
                    Pregunta = "¿Quiénes se adjudican vía Convenios Marco, sugún rubro?",
                    RedTitulo = "¿Quiénes se adjudican vía Convenios Marco, sugún rubro?  - Observatorio de Compras",
                    RedDescripcion = "El gráfico representa la distribución del uso de los Convenios Marco.",
                    RedUrl = "Quienes_se_adjudican_via_Convenios_Marco",
                    RedImagen = "Timg3_1.png"
                }
            );
            ListPostsConvenio.Add(
                new Post
                {
                    Id = 2,
                    Descripcion = "La visualización presenta las compras Servicio - Proveedor para el periodo seleccionado en el filtro presente a la derecha. El tamaño de la burbuja corresponde al porcentaje de compras que el municipio realiza al respectivo proveedor, y mientras que el color de las burbujas se puede seleccionar entre la cantidad de órdenes de compra o el monto comprado, tomando como referencia el mercado de compras totales del Ministerio seleccionado, en el período seleccionado. Es decir, a mayor tamaño de la burbuja, mayor la importancia de la relación comprador - proveedor sobre las compras del Servicio para el período seleccionado, y mientras más oscura sea la burbuja, mayor la cantidad de órdenes de compra o el monto transado respecto del mercado de compras del Ministerio.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1535851610683' style='position: relative'><noscript><a href='#'><img alt='Dashboard1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;6_&#47;6_mobile&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='6_mobile&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;6_&#47;6_mobile&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1535851610683');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*2.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1543521070401' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;CM&#47;CM2_0&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='CM2_0&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;CM&#47;CM2_0&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1543521070401');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "A_que_empresas_le_compra_el_Gobierno",
                    Pregunta = "¿A qué empresas le compra el Gobierno vía Convenios marco, según servicio público?",
                    RedTitulo = "¿A qué empresas le compra el Gobierno vía Convenios marco, según servicio público?  - Observatorio de Compras",
                    RedDescripcion = "La visualización presenta las compras Servicio - Proveedor en un periodo en especifico.",
                    RedUrl = "A_que_empresas_le_compra_el_Gobierno",
                    RedImagen = "Timg3_2.png"
                }
            );
        }
    }

    public class PostsEmpresas
    {

        public PostsEmpresas()
        {
            ListPostsEmpresas = new List<Post>();
            LoadPostDataEmpresas();
        }

        public List<Post> ListPostsEmpresas { get; set; }

        private void LoadPostDataEmpresas()
        {
            ListPostsEmpresas.Add(
                new Post
                {
                    Id=1,
                    Descripcion = "La visualización, presenta un estado general de un proveedor seleccionado, por ejemplo, la cantidad de transacciones, y su comparación con el promedio de esa métrica, esto con el fin de mostrar que tipo de Proveedor es. Asimismo, se presenta el nivel de éxito de las ofertas del proveedor en las licitaciones, mostrando la cantidad de ofertas versus la cantidad de adjudicaciones.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1538190376193' style='position: relative'><noscript><a href='#'><img alt='Nombre ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;7_&#47;7_mob&#47;Nombre&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='7_mob&#47;Nombre' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;7_&#47;7_mob&#47;Nombre&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1538190376193');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1538190373932' style='position: relative'><noscript><a href='#'><img alt='Por Nombre ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;7_&#47;7_231&#47;PorNombre&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='7_231&#47;PorNombre' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;7_&#47;7_231&#47;PorNombre&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1538190373932');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "Busca_por_Empresa_Nombre",
                    Pregunta = "Comportamiento de venta de Proveedores de tu interés - Por Nombre",
                    RedTitulo = "Comportamiento de venta de Proveedores de tu interés - Por Nombre  - Observatorio de Compras",
                    RedDescripcion = "La visualización presenta el estado general de un proveedor seleccionado. Por ejemplo, muestra la cantidad de transacciones por proveedor. Asimismo, se presenta el nivel de éxito de las ofertas del proveedor en las licitaciones, mostrando la cantidad de ofertas versus la cantidad de adjudicaciones.",
                    RedUrl = "Busca_por_Empresa_Nombre",
                    RedImagen = "Timg4_1.png"
                }
            );
            ListPostsEmpresas.Add(
                new Post
                {
                    Id = 2,
                    Descripcion = "La visualización, presenta un estado general de un proveedor seleccionado, por ejemplo, la cantidad de transacciones, y su comparación con el promedio de esa métrica, esto con el fin de mostrar que tipo de Proveedor es. Asimismo, se presenta el nivel de éxito de las ofertas del proveedor en las licitaciones, mostrando la cantidad de ofertas versus la cantidad de adjudicaciones.",
                    GraficoMobile = "<div class='tableauPlaceholder' id='viz1538190362972' style='position: relative'><noscript><a href='#'><img alt='rut ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;7_&#47;7_mob&#47;rut&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='7_mob&#47;rut' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;7_&#47;7_mob&#47;rut&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1538190362972');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    GraficoWeb = "<div class='tableauPlaceholder' id='viz1538190341136' style='position: relative'><noscript><a href='#'><img alt='Por RUT ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;7_&#47;7_231&#47;PorRUT&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='7_231&#47;PorRUT' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;7_&#47;7_231&#47;PorRUT&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1538190341136');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>",
                    IdUrl = "Busca_por_Empresa_Rut",
                    Pregunta = "Comportamiento de venta de Proveedores de tu interés - Por Rut",
                    RedTitulo = "Comportamiento de venta de Proveedores de tu interés - Por Rut  - Observatorio de Compras",
                    RedDescripcion = "La visualización presenta el estado general de un proveedor seleccionado. Por ejemplo, muestra la cantidad de transacciones por proveedor. Asimismo, se presenta el nivel de éxito de las ofertas del proveedor en las licitaciones, mostrando la cantidad de ofertas versus la cantidad de adjudicaciones.",
                    RedUrl = "Busca_por_Empresa_Rut",
                    RedImagen = "Timg4_1.png"
                }
            );
            ListPostsEmpresas.Add(
                new Post
                {
                    Id = 3,
                    GraficoMobile = "<iframe style='width: 100%;height: 100vh;border:0;overflow: hidden; ' src='../../Home/Helper'></iframe>",
                    GraficoWeb = "<iframe style='width: 100%;height: 100vh;border:0;overflow: hidden; ' src='../../Home/Helper'></iframe>",
                    Descripcion = "En la visualización se presenta un listado de socios directos de empresas que participan en una misma licitación con al menos dos empresas distintas. El periodo analizado corresponde a los años 2013 a 2017.Al posicionarse sobre una barra se despliega el detalle de las empresas pertenecientes a la persona, y con ellas los montos adjudicados, las ofertas realizadas y las adjudicaciones logradas. Las flechas rojas corresponden a licitaciones adjudicadas.",
                    IdUrl = "Busca_por_Socios",
                    Pregunta = "Socios que participan en una licitación con dos o más empresas",
                    RedTitulo = "Socios que participan en una licitación con dos o más empresas  - Observatorio de Compras",
                    RedDescripcion = "En la visualización se presenta un listado de socios directos de empresas que participan en una misma licitación con al menos dos empresas distintas.",
                    RedUrl = "Busca_por_Socios",
                    RedImagen = "Timg4_2.png"
                }
            );
            ListPostsEmpresas.Add(
                new Post
                {
                    Id = 4,
                    GraficoMobile = "<iframe style='width: 100%;height: 100vh;border:0;overflow: hidden; ' src='../../Home/Helper2'></iframe>",
                    GraficoWeb = "<iframe style='width: 100%;height: 100vh;border:0;overflow: hidden; ' src='../../Home/Helper2'></iframe>",
                    Descripcion = "En la visualización se presenta un listado de socios directos de empresas que participan en una misma licitación con al menos dos empresas distintas. El periodo analizado corresponde a los años 2013 a 2017.Al posicionarse sobre una barra se despliega el detalle de las empresas pertenecientes a la persona, y con ellas los montos adjudicados, las ofertas realizadas y las adjudicaciones logradas. Las flechas rojas corresponden a licitaciones adjudicadas.",
                    IdUrl = "Busca_por_Licitaciones",
                    Pregunta = "Licitaciones a las que postularon solo dos o más empresas del mismo Socio",
                    RedTitulo = "Licitaciones a las que postularon solo dos o más empresas del mismo Socio  - Observatorio de Compras",
                    RedDescripcion = "En la visualización se presentan las licitaciones a las que postularon SOLO dos o más empresas del mismo Socio. El periodo analizado corresponde a los años 2013 a 2017.Al posicionarse sobre un nodo se presentan los valores de cada tipo de nodo: Socio, Empresa, Licitación, y al posicionarse sobre los vínculos, se despliega el detalle de la relación",
                    RedUrl = "Busca_por_Licitaciones",
                    RedImagen = "Timg4_3.png"
                }
            );
        }
    }
}
